### ISSUE TITLE
[BUG] -  Sub components style tags not added in Storybook

### ISSUE THREAD

**Issue by Rensvl** [unplugin/unplugin-vue-ce#133]
### Describe the bug

Hi,

Subcomponent styling werkt zoals verwacht in de vite dev server, maar helaas als ik het via Storybook run, loop ik tegen issues aan. 

The sub web component styling works as expected in the vite dev server. In the reproduction example has the sub component a blue background, but when the same web component is running in storybook the blue background doesn’t appear. 

Could you please check if it can also be made functional in Storybook?

Thanks in advance.

Result in Storybook:
<img width="573" alt="Storybook" src="https://github.com/unplugin/unplugin-vue-ce/assets/10851159/2a66e6e2-1148-45d4-8908-c63e99b764c0">

Result in Vite dev server
<img width="561" alt="Vite dev server" src="https://github.com/unplugin/unplugin-vue-ce/assets/10851159/8333889e-f3c0-4889-bd85-482de9f414ea">

### Reproduction

https://codesandbox.io/p/devbox/great-shamir-whcvsl?file=%2Fpackage.json

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/unplugin/unplugin-vue-ce/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a unplugin-vue-ce issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/unplugin/unplugin-vue-ce/assets/32354856/959cbb59-2675-4fe8-a4f3-75238cd100cf)
This is because the module ID of vue in the storybook environment has changed, causing the code compilation to fail. I will update the code later.

**Comment by Rensvl** [comment]
Thanks for updating the code
