### ISSUE TITLE
 "Component is missing template or render function" when using in Vite's library mode.

### ISSUE THREAD

**Issue by mrcego** [unplugin/unplugin-vue-ce#91]
### Describe the bug

If we try building an library with Vite and then want to use in another project, "Component is missing template or render function" is shown, no matter where.

I'm combining ce-app and substyle for accomplish this. The reproduction is a monorepo with playground and package repos.

### Reproduction

https://github.com/mrcego/unplugin-vue-ce-library-attempt

### System Info

```Shell
SO: Windows 10/11
Browser: Chromium/Firefox
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
In the case you provided, I did not find that `ce-ui-core.js` was used in the playground, so I don’t know how you used it specifically, but I noticed that you used `createCEApp` incorrectly.
I made changes to the files in the package directory, and the alert component can be rendered.

```
// index.ts
import { createCEApp } from '@unplugin-vue-ce/ce-app'
import './style.css'
import Alert from '@components/Alert'

const ClgAlert = createCEApp(Alert.AlertBase)

// export individual elements
export { ClgAlert }

export function register() {
  ClgAlert.mount('clg-alert')
}
register()
```


```
// index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite + Vue + TS</title>
  </head>
  <body>
    <div id="app">
        <clg-alert></clg-alert>
    </div>
    <script type="module" src="/src/index.ts"></script>
  </body>
</html>

```

**Comment by mrcego** [comment]
I just built package folder using `pnpm build` and then `pnpm i` to do it part as project dependency, and tried using inside index.html from playground monorepo. My idea was the same as your example, exposing and using `register()` in playground monorepo directly.

**Comment by baiwusanyu-c** [comment]
The warning message about `Component is missing template or render function` is because you exported an object, so you need to make sure to pass in a specific component object.
`const ClgAlert = createCEApp(Alert.AlertBase)`

**Comment by mrcego** [comment]
Look like it's correct now, I missed miserably that detail 😊. In the other hand, I just ran in issue with slots, but this is another story. Thanks again @baiwusanyu-c.
